export const TEST_DISPATCH = 'TEST_DISPATCH';
// auth
export const GET_ERRORS = 'GET_ERRORS'; 
export const REQUEST_POST = 'REQUEST_POST';
export const RECEIVE_POST = 'RECEIVE_POST';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';


// session
export const REQUEST_GET_SESSION = 'REQUEST_GET_SESSION';
export const RESPONSE_GET_SESSION = 'RESPONSE_GET_SESSION';